#set(MC_MUJOCO_SHARE_DESTINATION "${CMAKE_INSTALL_PREFIX}/share/mc_mujoco")
find_package(mc_mujoco REQUIRED)
set(YAML_OUT "${CMAKE_CURRENT_BINARY_DIR}/nail.yaml")
configure_file(nail.in.yaml "${YAML_OUT}")
install(FILES "${YAML_OUT}"
        DESTINATION "${MC_MUJOCO_SHARE_DESTINATION}")
install(FILES "nail.xml"
        DESTINATION "${MC_MUJOCO_SHARE_DESTINATION}/object")
install(FILES "nail.stl"
        DESTINATION "${MC_MUJOCO_SHARE_DESTINATION}/object")